# Generated by Django 5.2.6 on 2025-09-06 15:34

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('description', models.TextField(blank=True)),
                ('serial_number', models.CharField(max_length=60)),
                ('units', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('power_watts', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Rack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('description', models.TextField(blank=True)),
                ('serial_number', models.CharField(max_length=60)),
                ('max_units', models.PositiveIntegerField()),
                ('max_power_watts', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DeviceAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assignment', to='inventory.device')),
                ('rack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='inventory.rack')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('device', 'rack')},
            },
        ),
    ]
